version: "3.8"

services:
  gamou:
    image: node:16.14.0
    container_name: gamou_app
    # restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    mem_limit: 2g
    memswap_limit: 2g
    cpus: "2"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
        reservations:
          memory: 2g

volumes:
  app_data:
