version: "3.8"

services:
  gamou:
    build: .
    ports:
      - 3000:3000
    container_name: gamou_app
    restart: always
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_USER=gamou_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=gamou_db
      - NEXT_PUBLIC_BASE_URL=https://gamou.app
      - TOKEN_SECRET=gamou_secret_token
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: gamou_db
    restart: always
    environment:
      POSTGRES_USER: gamou_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: gamou_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    environment:
      - ENV=production
      - APPLICATION_URL=http://gamou:3000
    restart: always

volumes:
  app_data:
  postgres_data:
