import { CartProvider } from "@/hooks/use-cart";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CompanyProvider } from "@/hooks/use-company";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {
          <CompanyProvider>
            <CartProvider>{children}</CartProvider>
          </CompanyProvider>
        }
      </body>
    </html>
  );
}
